// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0k_gDcyFlAWuKwayDHnCO4nYNAeiDGdw',
    appId: '1:132934703558:web:366fe940cc426983cdbac7',
    messagingSenderId: '132934703558',
    projectId: 'pilarproject',
    authDomain: 'pilarproject.firebaseapp.com',
    storageBucket: 'pilarproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8NkDEwFwj_iu1aHzOmNneWgIvoUI5Q8',
    appId: '1:132934703558:android:8a7f46e9dcc094d1cdbac7',
    messagingSenderId: '132934703558',
    projectId: 'pilarproject',
    storageBucket: 'pilarproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACDXFovfNa0EtDn8dpU_RgNDcZOZWmUL4',
    appId: '1:132934703558:ios:7e3f973d8ebc7011cdbac7',
    messagingSenderId: '132934703558',
    projectId: 'pilarproject',
    storageBucket: 'pilarproject.appspot.com',
    iosClientId:
        '132934703558-88f5tb7b7o8vqd1sff2put81riia0mfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACDXFovfNa0EtDn8dpU_RgNDcZOZWmUL4',
    appId: '1:132934703558:ios:7e3f973d8ebc7011cdbac7',
    messagingSenderId: '132934703558',
    projectId: 'pilarproject',
    storageBucket: 'pilarproject.appspot.com',
    iosClientId:
        '132934703558-88f5tb7b7o8vqd1sff2put81riia0mfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilarApp',
  );
}
